kind: pipeline
type: docker
name: cthunline-doc-ci

# when to execute pipeline
trigger:
  branch:
  - master
  - dev
  event:
  - push
  - pull_request

steps:
# install dependencies
- name: install
  image: node
  pull: if-not-exists
  commands:
  - npm ci
# linters
- name: lint
  image: node
  pull: if-not-exists
  depends_on:
  - install
  commands:
  - npm run lint
