kind: pipeline
type: docker
name: cthunline-doc-ci

# when to execute pipeline
trigger:
  branch:
  - master
  - dev
  event:
  - push
  - pull_request

steps:
# install dependencies
- name: install
  image: node:16-alpine
  pull: if-not-exists
  commands:
  - npm ci
# linters
- name: lint
  image: node:16-alpine
  pull: if-not-exists
  depends_on:
  - install
  commands:
  - npm run lint

---
kind: pipeline
type: docker
name: cthunline-doc-cd

# when to execute pipeline
trigger:
  branch:
  - master
  event:
  - push

# deploy on github pages
steps:
- name: deploy
  image: node
  pull: if-not-exists
  commands:
    - mkdir -p $HOME/.ssh
    - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
    - echo "$GITHUB_KEY" > "$HOME/.ssh/id_rsa"
    - chmod 600 $HOME/.ssh/id_rsa
    - npm i
    - npm run deploy
  environment:
    USE_SSH: true
    GIT_USER:
      from_secret: git_user
    GITHUB_KEY:
      from_secret: github_key
