# Meta data
openapi: '3.0.3'
info:
  version: 'v1.0'
  title: 'Cthunline REST API'

# API routes
paths:
  # Assets
  /api/assets:
    $ref: './references/paths/assets/assets.yaml'
  /api/assets/:assetId:
    $ref: './references/paths/assets/assets-id.yaml'
  /api/directories:
    $ref: './references/paths/assets/assets.yaml'
  /api/directories/:directoryId:
    $ref: './references/paths/assets/assets-id.yaml'
  # Authentication
  /api/auth:
    $ref: './references/paths/auth/auth.yaml'
  # Characters
  /api/characters:
    $ref: './references/paths/characters/characters.yaml'
  /api/characters/:characterId:
    $ref: './references/paths/characters/characters-id.yaml'
  /api/characters/:characterId/portrait:
    $ref: './references/paths/characters/characters-id-portrait.yaml'
  # Configuration
  /api/configuration:
    $ref: './references/paths/configuration/configuration.yaml'
  # Games
  /api/games:
    $ref: './references/paths/games/games.yaml'
  /api/games/{gameId}:
    $ref: './references/paths/games/games-id.yaml'
  # Notes
  /api/sessions/:sessionId/notes:
    $ref: './references/paths/notes/notes.yaml'
  /api/notes/:noteId:
    $ref: './references/paths/notes/notes-id.yaml'
  /api/notes/:noteId/:action:
    $ref: './references/paths/notes/notes-id-action.yaml'
  # Sessions
  /api/sessions:
    $ref: './references/paths/sessions/sessions.yaml'
  /api/sessions/:sessionId:
    $ref: './references/paths/sessions/sessions-id.yaml'
  # Sketchs
  /api/sketchs:
    $ref: './references/paths/sketchs/sketchs.yaml'
  /api/sketchs/:sketchId:
    $ref: './references/paths/sketchs/sketchs-id.yaml'
  # Users
  /api/users:
    $ref: './references/paths/users/users.yaml'
  /api/users/{userId}:
    $ref: './references/paths/users/users-id.yaml'
  /api/register:
    $ref: './references/paths/users/register.yaml'
  /api/invitation:
    $ref: './references/paths/users/invitation.yaml'

# Components
components:
  # Security
  securitySchemes:
    CookieAuth:
      type: 'apiKey'
      in: 'cookie'
      name: 'token'
      description: 'Authentication cookie'

security:
  - CookieAuth: []
