# Meta data
openapi: '3.0.3'
info:
  version: 'v1.0'
  title: 'Cthunline REST API'

# API routes
paths:
  # Configuration
  /api/configuration:
    $ref: './references/paths/configuration/configuration.yaml'
  # Authentication
  /api/auth:
    $ref: './references/paths/auth/auth.yaml'
  # Users
  /api/users:
    $ref: './references/paths/users/users.yaml'
  /api/users/{userId}:
    $ref: './references/paths/users/users-id.yaml'
  /api/register:
    $ref: './references/paths/users/register.yaml'
  /api/invitation:
    $ref: './references/paths/users/invitation.yaml'
  # Games
  /api/games:
    $ref: './references/paths/games/games.yaml'
  /api/games/{gameId}:
    $ref: './references/paths/games/games-id.yaml'
  # Assets
  /api/users/:userId/assets:
    $ref: './references/paths/assets/assets.yaml'
  /api/users/:userId/assets/:assetId:
    $ref: './references/paths/assets/assets-id.yaml'
  /api/users/:userId/directories:
    $ref: './references/paths/assets/assets.yaml'
  /api/users/:userId/directories/:directoryId:
    $ref: './references/paths/assets/assets-id.yaml'
  # Sessions
  /api/sessions:
    $ref: './references/paths/sessions/sessions.yaml'
  /api/sessions/:sessionId:
    $ref: './references/paths/sessions/sessions-id.yaml'
  /api/sessions/:sessionId/notes:
    $ref: './references/paths/sessions/notes.yaml'

# Components
components:
  # Security
  securitySchemes:
    CookieAuth:
      type: 'apiKey'
      in: 'cookie'
      name: 'token'
      description: 'Authentication cookie'

security:
  - CookieAuth: []
